### ISSUE TITLE
Project file's and folders structure

### ISSUE THREAD

**Issue by MoMakkawi** [KhaledAlhelwane/SOLID#1]
@KhaledAlhelwane See **[SOLID-Design-Principles](https://github.com/MoMakkawi/SOLID-Design-Principles)** repository that I published previously. I think it would be better for you in the future to publish in the same way of organizing the files that I adopted.

**Comment by KhaledAlhelwane** [comment]
Hello  @MoMakkawi, thanks a lot for your advice, I am reading your repo, it is very well organized and structured with deep information. 
I will imitate the way you wrote, as it seems to me very neat and clean, Thanks again
